CREATE TABLE `coupon` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `itemId` varchar(255) DEFAULT NULL COMMENT '商品id',
  `itemName` varchar(255) DEFAULT NULL COMMENT '商品名称',
  `pic` varchar(512) DEFAULT NULL COMMENT '商品主图',
  `detail` varchar(512) DEFAULT NULL COMMENT '商品详情页链接地址',
  `topClass` varchar(255) DEFAULT NULL COMMENT '商品一级类目',
  `tbkUrl` varchar(512) DEFAULT NULL COMMENT '淘宝客链接',
  `price` int(11) DEFAULT NULL COMMENT '商品价格(单位：分)',
  `saleCount` int(11) DEFAULT NULL COMMENT '商品月销量',
  `rate` int(11) DEFAULT NULL COMMENT '收入比率(%)',
  `income` int(11) DEFAULT NULL COMMENT '佣金',
  `ww` varchar(255) DEFAULT NULL COMMENT '卖家旺旺',
  `wwid` varchar(255) DEFAULT NULL COMMENT '卖家id',
  `store` varchar(255) DEFAULT NULL COMMENT '店铺名称',
  `platform` varchar(255) DEFAULT NULL COMMENT '平台类型',
  `couponId` varchar(255) DEFAULT NULL COMMENT '优惠券id',
  `couponCount` int(11) DEFAULT NULL COMMENT '优惠券总量',
  `leftCount` int(11) DEFAULT NULL COMMENT '优惠券剩余量',
  `couponPrice` varchar(255) DEFAULT NULL COMMENT '优惠券面额',
  `startDate` varchar(255) DEFAULT NULL COMMENT '优惠券开始时间',
  `endDate` varchar(255) DEFAULT NULL COMMENT '优惠券结束时间',
  `couponUrl` varchar(512) DEFAULT NULL COMMENT '优惠券链接',
  `uurl` varchar(512) DEFAULT NULL COMMENT '商品优惠券推广链接',
  `state` int(11) DEFAULT NULL COMMENT '状态',
  `kouling` varchar(255) DEFAULT NULL COMMENT '淘口令',
  `batchNo` varchar(255) DEFAULT NULL COMMENT '文件批次',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10001 DEFAULT CHARSET=utf8mb4 COMMENT='优惠券';